
==== Notes on Concepts:

* Meant for high level of security with ability to provide uninterrupted updates


* Updating of mirrors happens in three stages.
**    Update the external mirror from upstream.
**    Transfer the updated data onto a trusted storage device.
***	(Trusted storage seems to be physically connected to both the external and internal mirror servers)
**    Update the internal mirror from the trusted storage device.

* Seems like you have to manually copy the RMT data from the external to internal locations (on the shared storage)

* The download location of the container image is stored inside the Helm chart.
* To mirror container images inside the air gapped environment, you will run two container image registry services that are used to pull and in turn serve these images. 
** The registry service is shipped as a container image itself.

* We provide helm-mirror to allow downloading all charts present in a chart repository in bulk and moreover to extract all container image URLs from the charts. 
** skopeo is used to download all the images referred to in the Helm charts from their respective registry.
*** Helm charts will be provided to the internal network by a webserver and refer to the container images hosted on the internal registry mirror.

* Once mirroring is configured, you will not have to modify Dockerfile(s) or Kubernetes manifests to use the mirrors. 
** The requests are passed through the container engine which forwards them to the configured mirrors. 
*** For example: All images with a prefix registry.suse.com/ will be automatically pulled from the configured (internal) mirror instead.

==== Notes on 3.1.3 Requirements

* You will need to provide and maintain at least two machines in addition to your SUSE CaaS Platform cluster. 
** These mirror servers will reside on the external part of your network and the internal (air gapped) network respectively.
*** External: This machine will host the: 
**** Repository Mirroring Tool (RMT) for RPM packages and the 
**** container image registry for container images.
*** Internal: This machine will host the 
**** Repository Mirroring Tool (RMT) for RPM packages, and 
**** container image registry for container images as well as the 
**** Helm chart repository files.
** Ensure the container module and Repository Mirroring Tool is installed on both servers

* If you choose to add more container image registries to your internal network, these must run on different ports than the standard registry running on 5000. Configure your network to allow for this communication accordingly.

* The external mirror server must be able to exchange outgoing traffic with upstream sources on ports 80 and 443.
** All members of the SUSE CaaS Platform cluster must be able to communicate with the internal mirror server(s) within the air gapped network. 
*** You must configure at least these ports in all firewalls between the cluster and the internal mirror:
**** 80 HTTP - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 443 HTTPS - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 5000 HTTPS - Container image registry

* For the purposes of SSL, You need to define fully qualified domain names (FQDN) for both of the mirror servers in their respective network. 
* On the air gapped network, certificates need to cover the hostname of your server and the subdomains for the registry (registry.) and helm chart repository (charts.). 
** You must add corresponding aliases to the certificate.

TIP: You can use wildcard certificates to cover the entire hostname.

* The certificates can be replaced with the self-signed certificate, or you can re-use the certificates created by Repository Mirroring Tool (RMT) during the setup of the mirror servers.

* Place the certificate, CA certificate and key file in /etc/rmt/ssl/ as `rmt-server.crt`, `rmt-ca.cert`, and `rmt-server.key`.
** These certificates can be re-used by all three mirror services.
* Make sure the CA certificate is available to SUSE CaaS Platform system wide; so they can be used by the deployed components:
----
sudo cp /etc/rmt/ssl/rmt-ca.crt /etc/pki/trust/anchors/
sudo update-ca-certificates
----

* Transferring data from the external network mirror to the internal mirror can be performed in many ways. 
** The most common way is portable storage (USB keys or external hard drives).
*** In the following procedures, we will assume the storage (when connected) is mounted on /mnt/storage

==== Notes for 3.1.4 RPM Repository Mirror

* During the installation of Repository Mirroring Tool (RMT) use SCC creds for external, skip the SCC login for internal
* Need to disable automatic repository sync on internal mirror:
----
sudo systemctl stop rmt-server-sync.timer
sudo systemctl disable rmt-server-sync.timer
----

* 3.1.4.2 Client Configuration: https://documentation.suse.com/sles/15-SP1/single-html/SLES-rmt/#cha-rmt-client
** Seems pretty lengthy and not applicable with Terraform
*** Has sections for identifying the RMT server through boot parameters, AutoYaST, and with the `rmt-client-setup` command

==== Notes for 3.1.5 Updating RPM Repository Mirror

* The following procedure describes the transfer of data and mirrored RPMs between two RMT servers with a USB drive. 


* Sync and mirror the repos on the external RMT server, even if automatic mirroring is set:
----
rmt-cli sync
rmt-cli mirror
----
* Export RMT data on the external server to a USB drive:
** Mount a USB hard drive: `mount /dev/sdb1 /mnt/storage`
** Export the data about available repositories and products: `rmt-cli export data /mnt/storage/`
**  Export the list of enabled repositories: `rmt-cli export settings /mnt/storage/`
*** The exported file is required for exporting the repositories in the next step.
**  Export mirrored RPM packages: `rmt-cli export repos /mnt/storage`
*** Depending on the size of mirrored repositories, this can take a long time.


* Import RMT data on the internal server to a USB drive:
** Mount a USB hard drive: `mount /dev/sdb1 /mnt/storage`
** Import the data about available repositories and products: `rmt-cli import data /mnt/storage/`
** Import mirrored RPM packages: `rmt-cli import repos /mnt/storage`

NOTE: You can optionally export the RMT settings (as above) from the internal server and import them on the external server (`rmt-cli import settings /mnt/storage/`) to easily enable the repos required by the internal server. 

* Enable the required repos on the internal server as described in https://github.com/alexarnoldy/SUSE-tools/blob/master/Configure_RMT_Server.adoc

==== Notes on 3.1.6 Container Registry Mirror

* You can mirror images and charts from multiple registries in one shared internal registry. 
** We do not recommend mirroring multiple registries in a shared registry due to the potential conflicts.
** We highly recommend running separate helm chart and container registry mirrors for each source registry.
** Additional mirror registries must be run on separate mirror servers for technical reasons.

* You must download the registry container from SUSE and run it on the respective server.

* This list of base images can be found under the following link: https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
* Can also get a list of images with `skuba cluster images`

NOTE: For security reasons, the internal registry mirror is configured in read-only mode. 

NOTE: We will re-use the nginx webserver that is running as part of Repository Mirroring Tool (RMT) to act as a reverse proxy for the container image registry service and to serve the chart repository files. This step is not necessary for the external host.

===== Set Up Reverse Proxy and Virtual Host on the internal mirror server:
* Create a virtual host configuration file `/etc/nginx/vhosts.d/registry-server-https.conf`
** Replace mymirror.local below with the FQDN of the internal mirror server (Seems like the point is to use the FQDN that matches the SSL certs)
----
upstream docker-registry {
    server 127.0.0.1:5000;
}

map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
  '' 'registry/2.0';
}

server {
    listen 443   ssl;
    server_name  registry.`mymirror.local`;

    access_log  /var/log/nginx/registry_https_access.log;
    error_log   /var/log/nginx/registry_https_error.log;
    root        /usr/share/rmt/public;

    ssl_certificate     /etc/rmt/ssl/rmt-server.crt;
    ssl_certificate_key /etc/rmt/ssl/rmt-server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    location /v2/ {
      # Do not allow connections from docker 1.5 and earlier
      # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
      if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
        return 404;
      }

      ## If $docker_distribution_api_version is empty, the header is not added.
      ## See the map directive above where this variable is defined.
      add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

      proxy_pass                          http://docker-registry;
      proxy_set_header  Host              $http_host;   # required for docker client's sake
      proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_read_timeout                  900;
    }
}
----

* Create a virtual host configuration file `/etc/nginx/vhosts.d/charts-server-https.conf`
** Replace mymirror.local below with the FQDN of the internal mirror server (Seems like the point is to use the FQDN that matches the SSL certs)
----
server {
  listen 443   ssl;
  server_name  charts.`mymirror.local`;

  access_log  /var/log/nginx/charts_https_access.log;
  error_log   /var/log/nginx/charts_https_error.log;
  root        /srv/www/;

  ssl_certificate     /etc/rmt/ssl/rmt-server.crt;
  ssl_certificate_key /etc/rmt/ssl/rmt-server.key;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location /charts {
    autoindex on;
  }
}
----

* Restart nginx: `sudo systemctl restart nginx`

===== Set Up The External Registry and Helm Mirror Server

* `sudo zypper in docker helm-mirror skopeo`
* `sudo systemctl enable --now docker.service`
* `sudo docker pull registry.suse.com/sles12/registry:2.6.2`
* Save the pulled image to a .tar file: `sudo docker save -o /tmp/registry.tar registry.suse.com/sles12/registry:2.6.2`
* Create basic authentication credentials for the container image registry (Replace USERNAME and PASSWORD with credentials of your choice):
----
sudo mkdir -p /etc/docker/registry/{auth,certs}
sudo docker run --entrypoint htpasswd registry.suse.com/sles12/registry:2.6.2 -Bbn <USERNAME> <PASSWORD> | sudo tee /etc/docker/registry/auth/htpasswd
----
* Create the /etc/docker/registry/config.yml configuration file:
----
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
threshold: 3
----

NOTE: Setting up required authentication seems to break when using CRI-O as the client so the internal registry does not use any authentication.






// vim: set syntax=asciidoc:
