
==== Notes on Concepts:

* Meant for high level of security with ability to provide uninterrupted updates


* Updating of mirrors happens in three stages.
**    Update the external mirror from upstream.
**    Transfer the updated data onto a trusted storage device.
***	(Trusted storage seems to be physically connected to both the external and internal mirror servers)
**    Update the internal mirror from the trusted storage device.

* Seems like you have to manually copy the RMT data from the external to internal locations (on the shared storage)

* The download location of the container image is stored inside the Helm chart.
* To mirror container images inside the air gapped environment, you will run two container image registry services that are used to pull and in turn serve these images. 
** The registry service is shipped as a container image itself.

* We provide helm-mirror to allow downloading all charts present in a chart repository in bulk and moreover to extract all container image URLs from the charts. 
** skopeo is used to download all the images referred to in the Helm charts from their respective registry.
*** Helm charts will be provided to the internal network by a webserver and refer to the container images hosted on the internal registry mirror.

* Once mirroring is configured, you will not have to modify Dockerfile(s) or Kubernetes manifests to use the mirrors. 
** The requests are passed through the container engine which forwards them to the configured mirrors. 
*** For example: All images with a prefix registry.suse.com/ will be automatically pulled from the configured (internal) mirror instead.

==== Notes on 3.1.3 Requirements

* You will need to provide and maintain at least two machines in addition to your SUSE CaaS Platform cluster. 
** These mirror servers will reside on the external part of your network and the internal (air gapped) network respectively.
*** External: This machine will host the: 
**** Repository Mirroring Tool (RMT) for RPM packages and the 
**** container image registry for container images.
*** Internal: This machine will host the 
**** Repository Mirroring Tool (RMT) for RPM packages, and 
**** container image registry for container images as well as the 
**** Helm chart repository files.
** Ensure the container module and Repository Mirroring Tool is installed on both servers

* If you choose to add more container image registries to your internal network, these must run on different ports than the standard registry running on 5000. Configure your network to allow for this communication accordingly.

* The external mirror server must be able to exchange outgoing traffic with upstream sources on ports 80 and 443.
** All members of the SUSE CaaS Platform cluster must be able to communicate with the internal mirror server(s) within the air gapped network. 
*** You must configure at least these ports in all firewalls between the cluster and the internal mirror:
**** 80 HTTP - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 443 HTTPS - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 5000 HTTPS - Container image registry

* For the purposes of SSL, You need to define fully qualified domain names (FQDN) for both of the mirror servers in their respective network. 
* On the air gapped network, certificates need to cover the hostname of your server and the subdomains for the registry (registry.) and helm chart repository (charts.). 
** You must add corresponding aliases to the certificate.

TIP: You can use wildcard certificates to cover the entire hostname.

* The certificates can be replaced with the self-signed certificate, or you can re-use the certificates created by Repository Mirroring Tool (RMT) during the setup of the mirror servers.

* Place the certificate, CA certificate and key file in /etc/rmt/ssl/ as `rmt-server.crt`, `rmt-ca.cert`, and `rmt-server.key`.
** These certificates can be re-used by all three mirror services.
* Make sure the CA certificate is available to SUSE CaaS Platform system wide; so they can be used by the deployed components:
----
sudo cp /etc/rmt/ssl/rmt-ca.crt /etc/pki/trust/anchors/
sudo update-ca-certificates
----

* Transferring data from the external network mirror to the internal mirror can be performed in many ways. 
** The most common way is portable storage (USB keys or external hard drives).
*** In the following procedures, we will assume the storage (when connected) is mounted on /mnt/storage

==== Notes for 3.1.4 RPM Repository Mirror

* During the installation of Repository Mirroring Tool (RMT) use SCC creds for external, skip the SCC login for internal
* Need to disable automatic repository sync on internal mirror:
----
sudo systemctl stop rmt-server-sync.timer
sudo systemctl disable rmt-server-sync.timer
----

* 3.1.4.2 Client Configuration: https://documentation.suse.com/sles/15-SP1/single-html/SLES-rmt/#cha-rmt-client
** Seems pretty lengthy and not applicable with Terraform
*** Has sections for identifying the RMT server through boot parameters, AutoYaST, and with the `rmt-client-setup` command

==== Notes for 3.1.5 Updating RPM Repository Mirror

* The following procedure describes the transfer of data and mirrored RPMs between two RMT servers with a USB drive. 

NOTE: The server `sun` is connected to the SUSE Customer Center, while `sirius` is a server in an air-gapped network. 

* Sync and mirror the repos on the external RMT server, even if automatic mirroring is set:
----
rmt-cli sync
rmt-cli mirror
----
* Mount a USB hard drive: `mount /dev/sdb1 /mnt/storage`
* Export the data about available repositories and products: `rmt-cli export data /mnt/storage/`







// vim: set syntax=asciidoc:
