
==== Notes on Concepts:

* Meant for high level of security with ability to provide uninterrupted updates


* Updating of mirrors happens in three stages.
**    Update the external mirror from upstream.
**    Transfer the updated data onto a trusted storage device.
***	(Trusted storage can be be physically connected to both the external and internal mirror servers, or a separate device such as a USB drive)
**    Update the internal mirror from the trusted storage device.

* Seems like you have to manually copy the RMT data from the external to internal locations (on the shared storage)

* The download location of required container images is stored inside the Helm chart.
* To mirror container images inside the air gapped environment, you will run two container image registry services that are used to pull and in turn serve these images. 
** The registry service is shipped as a container image itself.

* We provide helm-mirror to allow downloading all charts present in a chart repository in bulk and moreover to extract all container image URLs from the charts. 
** skopeo is used to download all the images referred to in the Helm charts from their respective registry.
*** Helm charts will be provided to the internal network by a webserver and refer to the container images hosted on the internal registry mirror.

* Once mirroring is configured, you will not have to modify Dockerfile(s) or Kubernetes manifests to use the mirrors. 
** The requests are passed through the container engine which forwards them to the configured mirrors. 
*** For example: All images with a prefix registry.suse.com/ will be automatically pulled from the configured (internal) mirror instead.

==== Notes on 3.1.3 Requirements

* You will need to provide and maintain at least two machines in addition to your SUSE CaaS Platform cluster. 
** These mirror servers will reside on the external part of your network and the internal (air gapped) network respectively.
*** External: This machine will host the: 
**** Repository Mirroring Tool (RMT) for RPM packages and the 
**** container image registry for container images.
*** Internal: This machine will host the: 
**** Repository Mirroring Tool (RMT) for RPM packages, and 
**** container image registry for container images as well as the 
**** Helm chart repository files.


* If you choose to add more container image registries to your internal network, these must run on different ports than the standard registry running on 5000. Configure your network to allow for this communication accordingly.

* The external mirror server must be able to exchange outgoing traffic with upstream sources on ports 80 and 443.
** All members of the SUSE CaaS Platform cluster must be able to communicate with the internal mirror server(s) within the air gapped network. 
*** You must configure at least these ports in all firewalls between the cluster and the internal mirror:
**** 80 HTTP - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 443 HTTPS - Repository Mirroring Tool (RMT) Server and Helm chart repository mirror
**** 5000 HTTPS - Container image registry

* For the purposes of SSL, You need to define fully qualified domain names (FQDN) for both of the mirror servers in their respective network. 
* On the air gapped network, certificates need to cover the hostname of your server and the subdomains for the registry (registry.) and helm chart repository (charts.). 
** You must add corresponding aliases to the certificate.

TIP: You can use wildcard certificates to cover the entire hostname.

* The certificates can be replaced with the self-signed certificate, or you can re-use the certificates created by Repository Mirroring Tool (RMT) during the setup of the mirror servers.

* Place the certificate, CA certificate and key file in /etc/rmt/ssl/ as `rmt-server.crt`, `rmt-ca.cert`, and `rmt-server.key`.
** These certificates can be re-used by all three mirror services.
* Make sure the CA certificate is available to SUSE CaaS Platform system wide; so they can be used by the deployed components:
----
sudo cp /etc/rmt/ssl/rmt-ca.crt /etc/pki/trust/anchors/
sudo update-ca-certificates
----

* Transferring data from the external network mirror to the internal mirror can be performed in many ways. 
** The most common way is portable storage (USB keys or external hard drives).
*** In the following procedures, we will assume the storage (when connected) is mounted on /mnt/storage

==== Notes for 3.1.4 RPM Repository Mirror

* Install RMT on both servers, per: https://github.com/alexarnoldy/SUSE-tools/blob/master/Configure_RMT_Server.adoc
** Ensure the container module and Repository Mirroring Tool is installed on both servers
** When prompted to provide SCC "Organizational Credentials" on the first page of RMT configuration: 
*** Provide the credentials for the External Server
*** For the Internal Server, use "Next" and "Ignore and continue" to skip providing credentials 
** Do not sync and mirror repos on the Internal Server

* Need to disable automatic repository sync on internal mirror:
----
sudo systemctl stop rmt-server-sync.timer
sudo systemctl disable rmt-server-sync.timer
----

* 3.1.4.2 Client Configuration: https://documentation.suse.com/sles/15-SP1/single-html/SLES-rmt/#cha-rmt-client
** Seems pretty lengthy and not applicable with Terraform
*** Has sections for identifying the RMT server through boot parameters, AutoYaST, and with the `rmt-client-setup` command

==== Notes for 3.1.5 Updating RPM Repository Mirror

* The following procedure describes the transfer of data and mirrored RPMs between two RMT servers with a USB drive. 

* Sync and mirror the repos on the External RMT Server, even if automatic mirroring is set:
----
sudo rmt-cli sync
sudo rmt-cli mirror
----
* Export RMT data on the external server to a USB drive:
** Mount a USB hard drive: `sudo mount /dev/vdb1 /mnt/storage`
** Ensure the _rmt server can write to the storage: `sudo chown _rmt:nginx /mnt/storage/`
** Export the data about available repositories and products: `sudo rmt-cli export data /mnt/storage/`
**  Export the list of enabled repositories: `sudo rmt-cli export settings /mnt/storage/`
*** The exported file is required for exporting the repositories in the next step.
**  Export mirrored RPM packages: `sudo rmt-cli export repos /mnt/storage`
*** Depending on the size of mirrored repositories, this can take a long time.
** Unmount the USB hard drive and move it to the Internal Mirror Server


* Import RMT data on the Internal Mirror Server to a USB drive:
** Mount a USB hard drive: `sudo mount /dev/vdb1 /mnt/storage`
** Import the data about available repositories and products: `rmt-cli import data /mnt/storage/`
** Import mirrored RPM packages: `rmt-cli import repos /mnt/storage`

NOTE: You can optionally export the RMT settings (as above) from the internal server and import them on the external server (`rmt-cli import settings /mnt/storage/`) to easily enable the repos required by the internal server. 

* Enable the required repos on the internal server as described in https://github.com/alexarnoldy/SUSE-tools/blob/master/Configure_RMT_Server.adoc

==== Notes on 3.1.6 Container Registry Mirror

* You can mirror images and charts from multiple registries in one shared internal registry. 
** We do not recommend mirroring multiple registries in a shared registry due to the potential conflicts.
** We highly recommend running separate helm chart and container registry mirrors for each source registry.
** Additional mirror registries must be run on separate mirror servers for technical reasons.

* You must download the registry container from SUSE and run it on the respective server.

* This list of base images can be found under the following link: https://documentation.suse.com/external-tree/en-us/suse-caasp/4/skuba-cluster-images.txt
* Can also get a list of images with `skuba cluster images`

NOTE: For security reasons, the internal registry mirror is configured in read-only mode. 

NOTE: We will re-use the nginx webserver that is running as part of Repository Mirroring Tool (RMT) to act as a reverse proxy for the container image registry service and to serve the chart repository files. This step is not necessary for the external host.

===== Set Up Reverse Proxy and Virtual Host on the internal mirror server:
* Create a virtual host configuration file `/etc/nginx/vhosts.d/registry-server-https.conf`
** Replace mymirror.local below with the FQDN of the internal mirror server (Seems like the point is to use the FQDN that matches the SSL certs)
----
upstream docker-registry {
    server 127.0.0.1:5000;
}

map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
  '' 'registry/2.0';
}

server {
    listen 443   ssl;
    server_name  registry.`mymirror.local`;

    access_log  /var/log/nginx/registry_https_access.log;
    error_log   /var/log/nginx/registry_https_error.log;
    root        /usr/share/rmt/public;

    ssl_certificate     /etc/rmt/ssl/rmt-server.crt;
    ssl_certificate_key /etc/rmt/ssl/rmt-server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    location /v2/ {
      # Do not allow connections from docker 1.5 and earlier
      # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
      if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
        return 404;
      }

      ## If $docker_distribution_api_version is empty, the header is not added.
      ## See the map directive above where this variable is defined.
      add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

      proxy_pass                          http://docker-registry;
      proxy_set_header  Host              $http_host;   # required for docker client's sake
      proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_read_timeout                  900;
    }
}
----

* Create a virtual host configuration file `/etc/nginx/vhosts.d/charts-server-https.conf`
** Replace mymirror.local below with the FQDN of the internal mirror server (Seems like the point is to use the FQDN that matches the SSL certs)
----
server {
  listen 443   ssl;
  server_name  charts.`mymirror.local`;

  access_log  /var/log/nginx/charts_https_access.log;
  error_log   /var/log/nginx/charts_https_error.log;
  root        /srv/www/;

  ssl_certificate     /etc/rmt/ssl/rmt-server.crt;
  ssl_certificate_key /etc/rmt/ssl/rmt-server.key;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location /charts {
    autoindex on;
  }
}
----

* Restart nginx: `sudo systemctl restart nginx`

===== Set Up The External Registry and Helm Mirror Server

* `sudo zypper in docker helm-mirror skopeo`
* `sudo systemctl enable --now docker.service`
* `sudo docker pull registry.suse.com/sles12/registry:2.6.2`
* Ensure the USB drive is mounted under /mnt/storage: `df -h`
* Save the pulled image to a .tar file on the USB drive: `sudo docker save -o /mnt/storage/registry.tar registry.suse.com/sles12/registry:2.6.2`
* Create basic authentication credentials for the container image registry (Replace USERNAME and PASSWORD with credentials of your choice):
----
sudo mkdir -p /etc/docker/registry/{auth,certs}
sudo docker run --entrypoint htpasswd registry.suse.com/sles12/registry:2.6.2 -Bbn <USERNAME> <PASSWORD> | sudo tee /etc/docker/registry/auth/htpasswd
----
* Create the /etc/docker/registry/config.yml configuration file:
----
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
threshold: 3
----

NOTE: Setting up required authentication seems to break when using CRI-O as the client so the internal registry does not use any authentication.

* Run the registry container:
----
sudo docker run -d -p 5000:5000 -v /etc/rmt/ssl:/etc/rmt/ssl:ro --restart=always --name registry \
-v /etc/docker/registry:/etc/docker/registry:ro \
-v /var/lib/registry:/var/lib/registry registry.suse.com/sles12/registry:2.6.2
----

===== Set Up The Internal Registry and Helm Mirror Server

* `sudo zypper in docker`
* `sudo systemctl enable --now docker.service`
* Connect the USB drive to the internal mirror server and mount it under /mnt/storage
* `sudo docker load -i /mnt/storage/registry.tar`
* `sudo mkdir -p /etc/docker/registry/`
* Create the `/etc/docker/registry/config.yml` configuration file
----
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    readonly:
      enabled: true
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /etc/rmt/ssl/rmt-server.crt
    key: /etc/rmt/ssl/rmt-server.key
health:
  storagedriver:
    enabled: true
    interval: 10s
threshold: 3
----

* Run the registry container:
----
sudo docker run -d -p 5000:5000 -v /etc/rmt/ssl:/etc/rmt/ssl:ro --restart=always --name registry \
-v /etc/docker/registry:/etc/docker/registry:ro \
-v /var/lib/registry:/var/lib/registry registry.suse.com/sles12/registry:2.6.2
----

==== Notes from 3.1.6.2 Client Configuration

NOTE: The instructions for this steps are a little strangely worded, but it seems like all cluster nodes need to have this update to point to the internal mirror rather than the Internet registries.

* Update `/etc/containers/registries.conf` on all cluster nodes:
** Comment out all existing entries
* Add these V2 compatible entries, as appropriate. Change `registry01.mydomain.local` to match the FQDN of the internal mirror server:
----
[[registry]]
prefix = "registry.suse.com"
location = "registry01.mydomain.local:5000/registry.suse.com"
[[registry]]
prefix = "docker.io"
location = "registry01.mydomain.local:5000/docker.io"
[[registry]]
prefix = "docker.io/library"
location = "registry01.mydomain.local:5000/docker.io"
[[registry]]
prefix = "quay.io"
location = "registry01.mydomain.local:5000/quay.io"
[[registry]]
prefix = "k8s.gcr.io"
location = "registry01.mydomain.local:5000/k8s.gcr.io"
[[registry]]
prefix = "gcr.io"
location = "registry01.mydomain.local:5000/gcr.io"
----

CAUTION: The problem with this step is that earlier in the procedure it cautions against using the same server for more than one mirrored registry. 


==== Notes from 3.1.7 Helm Chart Repository Mirror

NOTE: The helm charts will require images available from a registry mirror. The charts themselves are served on a simple webserver and do not require any particular configuration apart from basic networking availability and a hostname.

* All nodes on the internal (air-gapped) network that run helm, i.e. the admin node, must update helm to point to the webserver on the internal mirror: `helm repo add <SUSE_MIRROR> https://charts.mydomain.local`
** Replace `<SUSE_MIRROR>` with a repo name that contains lower case letters and numbers and may be separated with dashes

==== 3.1.8 Updating Registry Mirror And Helm Charts

NOTE: There is no need to stop the container image registry services while doing the update procedures. All changed images will be re-indexed automatically.

===== Pull Data From Upstream Sources into the External Mirror Server

* Download all charts from the https://kubernetes-charts.suse.com repository to `/tmp/charts`
** Change `mydomain.local` to match the FQDN of the INTERNAL Mirror Server

----
mkdir /tmp/charts
cd /tmp/charts
helm-mirror --new-root-url http://charts.mydomain.local https://kubernetes-charts.suse.com /tmp/charts
----

* Translate the chart information into the skopeo format:
----
mkdir /tmp/skopeodata
helm-mirror --ignore-errors inspect-images /tmp/charts -o skopeo=sync.yaml
----

NOTE: The helm-mirror tool will attempt to render and inspect all downloaded charts. Some charts will have values that are filled from environment data on their source repository and produce errors. The --ignore-errors flag is used to complete the command regardless of these errors.

* Download all the referenced images using skopeo: `skopeo sync --source-yaml sync.yaml dir:/tmp/skopeodata`
** skopeo will automatically create a directory named after the hostname of the registry from which you are downloading the images. 
*** The final path will be something like /tmp/skopeodata/registry.suse.com/ .

* Populate the local, external mirror server registry with the downloaded data:
** In the command below, use the same USERNAME and PASSWORD you configured above in the step "Set Up The External Registry and Helm Mirror Server"
** Change `mydomain.local` to match the FQDN of the INTERNAL Mirror Server
----
skopeo sync --dest-creds USERNAME:PASSWORD \
dir:/tmp/skopeodata/registry.suse.com/ docker://mydomain.local:5000
----
* After synchronization completes, remove the /tmp/skopeodata directory: `rm -rf /tmp/skopeodata`
* Mount the USB drive to the External Mirror Server: `mount /dev/sdb1 /mnt/storage`
* Rsync the container image data to the USB drive: `rsync -aP /var/lib/registry/ /mnt/storage/registry/ --delete`
* Rsync the helm chart data to the USB drive: `rsync -aP /tmp/charts/ /mnt/storage/charts --delete`
* Unmount the USB drive and move it to the Internal Mirror Server

* Mount the USB drive to the INTERNAL Mirror Server: `mount /dev/sdb1 /mnt/storage`
* Rsync the container image data to the internal registry: `rsync -aP /mnt/storage/registry/ /var/lib/registry/ --delete`
* Rsync the helm chart data to the internal web server: `rsync -aP /mnt/storage/charts/ /srv/www/charts/ --delete`
* Set the appropriate file ownership and permissions: `sudo chown -R nginx:nginx /srv/www/charts && sudo chmod -R 555 /srv/www/charts/`

* All nodes on the internal (air-gapped) network that run helm, i.e. the admin node, should update their local helm charts from the Internal Mirror Server: `helm repo update`





// vim: set syntax=asciidoc:
