### State of document: Creating
### Purpose of document: To provide a quick deployment of the RMT server based on a limited set of parameters
#### Aspirations: Eventually, to containerize this work

#### Based in part on https://github.com/SUSE/rmt  and https://documentation.suse.com/sles/15-SP1/single-html/SLES-rmt/#book-rmt

#### Install the server and database
* Install and register the base O/S
* Activate the server applications module: `sudo SUSEConnect -p sle-module-server-applications/15.1/x86_64`
* Install RMT with YaST installation wizard: `sudo zypper --non-interactive install rmt-server yast2-rmt`
* Configure the RMT server: `sudo yast2 rmt`
* Review the version of SLES on the RMT server: `cat /etc/*release`
* Add the RMT repository for the version of SLES: 
** Set the DIST variable below appropriately, from the choices of: `SLE_15, SLE_15_SP1, openSUSE_Leap_15.0, openSUSE_Leap_15.1, openSUSE_Tumbleweed` 
** `export DIST=`
** `zypper ar -f https://download.opensuse.org/repositories/systemsmanagement:/SCC:/RMT/${DIST}/systemsmanagement:SCC:RMT.repo`
* Install the RMT server: `sudo zypper --non-interactive install rmt-server`

#### Prepare the database and start the RMT server
* Ensure the database is running: `systemctl status mysql`
* Make sure you can access to the database `mysql -u root -p`
** Provide the database root user password
** Use the key sequence `\q` to exit the database shell
* Create the database `rmt` user:
----
mysql -u root -p <<EOF
GRANT ALL PRIVILEGES ON \`rmt\`.* TO rmt@localhost IDENTIFIED BY 'rmt';
FLUSH PRIVILEGES;
EOF
----
* Ensure the RMT server is running: `systemctl status rmt-server`


#### Sync and mirror the needed repositories

TIP: Virtually all installations will need the "SUSE Linux Enterprise Server" and "Basesystem Module", for the appropriate version of SLES, to be enabled. In addition, many applications need the "Server Applications Module" to be enabled. Systems that need a desktop environment need the Desktop Applications Module" to be enabled. Certain products, like CaaS Platform, require other repositories to be enabled such as the "Containers Module". 

.There are several ways of determining which repositories need to be enabled for a SUSE application:
* Run the command `sudo SUSEConnect -s | grep --color Registered` on a system that has the required application installed and registered correctly
* Search for the word SUSEConnect in the application's installation and/or deployment guide
* Start the installation of a SLES VM and, after registering SLES with the SUSE Customer Center, select the desired application. All additionally required repositories will be automatically selected

.Gather all of the product ID's for the modules to be enabled
* Take note of the product ID's (in the first column) and the version numbers (in the third column); for all products to be mirrored locally: `sudo rmt-cli product list --all | less`

TIP: The same command can be used to verify which products are currently enabled to be mirrored and when they were last mirrored.

IMPORTANT: The RMT server must be registered for all products that will be mirrored to it.

* Enable mirroring for the desired products: `sudo rmt-cli product enable <space separated list of product IDs>`
* Synchronize the repository meta data from the SUSE Customer Center `sudo rmt-cli sync`
* Mirror the desired repositories to the RMT server `nohup sudo rmt-cli mirror`

IMPORTANT: AutoYaST clients will receive the software, but not automatically register with the RMT server. To regisiter a client use `sudo SUSEConnect --url http://<rmt server>` or `sudo SUSEConnect --url http://<rmt server> -p <product, i.e. caasp/4.0/x86_64>`

// vim: set syntax=asciidoc:
